### ISSUE TITLE
Can't edit site when using GitHub orgs and teams

### ISSUE THREAD

**Issue by patcon** [timwis/jkan#102]
Really cool tool!

The login-and-edit feature in the top-right worked when my personal account owned the repo, but when I transferred the app and repo to the CivicTechTO organization, with a write-perm team that I was a member of having access, then it no longer allows me to perform an logged-in tasks

**Comment by timwis** [comment]
Thanks @patcon! I'm having trouble reproducing the issue you described. I created a [test org](https://github.com/timwis-test-org), added a [test user](https://github.com/timwis-test) on a new team, and gave that team _write_ access to the _jkan_ repo. I was then able to login to the site as that user and add a [dataset](http://timwis-test-org.github.io/jkan/datasets/created-by-collaborator/) using the form.

Could the issue be perhaps that you don't have write access to the repo on that team? (The default permission is _read_)

![screen shot 2016-04-19 at 06 10 10](https://cloud.githubusercontent.com/assets/761444/14635661/6dca1fb6-05f5-11e6-8ab3-76ee4ff8ba06.png)

**Comment by patcon** [comment]
Hm. Yes, as far as I can tell, it's the same, aisde from the "how-i-got-there process of transferring the repo and app from a user account to the org.

Let me see if I can reproduce on a new org later, and I'll add you as admin so you can see anything i can

**Comment by timwis** [comment]
Sounds good

**Comment by chriswhong** [comment]
@patcon Did you figure this out?  I just did the same thing (forked JKAN into a github org) and am getting 404s on the attempts to update files.  I have verified that I have write permissions on the repo, and everything looks in order for gatekeeper.

**Comment by chriswhong** [comment]
Got it working... turns out the Oauth Application in github was under my personal account, and I had to authorize the org to use it.
