### ISSUE TITLE
Pull organization logos from Twitter accounts

### ISSUE THREAD

**Issue by patcon** [timwis/jkan#106]
Lots of organizational units have Twitter accounts. These twitter accounts either have official logos, or when lacking, imagery that the bureaucracy has approved as a suitable stand-in. Seems possible to add a twitter handle onto an org, and use that :)

**Comment by timwis** [comment]
That's a clever idea @patcon. Although...couldn't they just "Copy Image URL" of the twitter account's logo and put that in instead?

**Comment by patcon** [comment]
Yep, totally could do by hand.

**Comment by timwis** [comment]
Okay sounds good. Feel free to re-open this issue if we think of a cleverer way around it
