### ISSUE TITLE
Start using font-awesome for iconography

### ISSUE THREAD

**Issue by patcon** [timwis/jkan#110]

**Comment by timwis** [comment]
Hi @patcon, JKAN does [use](https://github.com/timwis/jkan/blob/gh-pages/_includes/head.html#L16) font-awesome for icons on buttons and such. I assume you mean for the categories on the landing page? I'd love to, but font awesome is actually a bit limited in terms of icons that resemble "budget / finance," "public safety," etc. If you know of an icon library that has those, I'd much prefer them over the static black images we currently use.

**Comment by patcon** [comment]
Ah sorry for the noise! Assumed :/
