### ISSUE TITLE
help me for links!

### ISSUE THREAD

**Issue by iltempe** [timwis/jkan#114]
I've changed a fork of JKAN from
territoriopen.github.io/website to 
territoriopen.github.io/ name of repo

I've changed base URL from /website in / in _config file but now when i click con links they send me in http://territoriopen.github.io/website links and i see error? why?

Repo is https://github.com/TerritoriOpen/territoriopen.github.io

thanks

**Comment by patcon** [comment]
Sorry to state obvious, but make sure you're refreshing the browser page to flush the cache -- this could me a few times

**Comment by timwis** [comment]
Hi @iltempe, it looks like you've changed it back to `/website` so I can't reproduce the issue. Have you seen [the wiki page on this](https://github.com/timwis/jkan/wiki/Custom-domain)? I would suggest changing `baseurl` to an empty string `""` instead of `/`.
