### ISSUE TITLE
Heroku Authorization Failure

### ISSUE THREAD

**Issue by ChrisCardoz** [timwis/jkan#123]
I followed the installation instructions on the JKAN demo website and was able to access the new site created by forking the old repo and authorizing with Heroku. However, whenever I try to login, I get a 404 error, and am directed to the url "https://github.com/login/oauth/authorize?client_id=45ceb4162a2afd229b11&redirect_uri=https%3A%2F%2Fchriscardoz.github.io%2Fjkan-1%2Fcategories%2F&scope=public_repo"

Here are my configuration variables:

**Comment by timwis** [comment]
Hi @ChrisCardoz! Happy to help. Fist though, the configuration variables are meant to be kept a secret (so no one else can use them) - particularly the `OAUTH_CLIENT_SECRET`, so you may want to remove the screenshot above (looks good anyway) and reset your secret by going to your [applications](https://github.com/settings/developers), selecting the one you created, and clicking `Reset client secret`. Following that you can modify your configuration variables in heroku to update it.

Could you link me to the repo you're working with? The one on your personal github account appears to be using the `master` branch somehow.

Also, when you setup the "application" on GitHub (to get the ID/secret), what "callback url" did you use? Did you tick the "public repo" permission box?

Happy to hop on a call this week as we discussed over email as well.

**Comment by ChrisCardoz** [comment]
Hey @timwis, here is the repo I'm working in: https://github.com/ChrisCardoz/jkan-1
The url for the cite is https://chriscardoz.github.io/jkan-1/ though it isn't complete yet. 
I'm not entirely sure about whether or not I checked the permission box. I responded to your most recent email about setting up a time to call, as I believe this will be the easiest way to solve the issues I'm having.

**Comment by timwis** [comment]
Revolved via phone
