### ISSUE TITLE
Remove "theme" key from _config

### ISSUE THREAD

**Issue by patcon** [timwis/jkan#127]
Not sure if there was a change in GitHub Pages, but this seems to cause issues now:
https://github.com/timwis/jkan/blob/gh-pages/_config.yml#L8

I removed the key completely and it works fine. Might have also been the titlecasing :)

**Comment by timwis** [comment]
Interesting -- what was the issue it was causing? That setting is used to change the JKAN theme (bootswatch).

**Comment by patcon** [comment]
In the repo settings page where GH pages build status shows up, it said there was a problem building, and that that theme was unknown

**Comment by timwis** [comment]
Gah! https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/ ...thanks github..

**Comment by timwis** [comment]
Looks like it'd be pretty easy to use a different variable, like `jkan_theme`, but I'm concerned about the fact that it essentially broke editing functionality on every JKAN instance... [I just tweeted github about it](https://twitter.com/timwis/status/782637801800101888)

**Comment by timwis** [comment]
So GitHub replied suggesting that this will be resolved in Jekyll 3.3 per jekyll/jekyll#5189. Unless I'm misreading that thread, it doesn't look like it will resolve this issue.

I think the only thing we can do is change the property for now, and hopefully any existing JKAN users will upgrade. Unless you can think of another idea? I suppose we could submit pull requests to all forks...

**Comment by timwis** [comment]
This is resolved in `v1.0.3` so closing the thread. But please respond if you have any other ideas on how we can notify users to upgrade, or make it work for them?

**Comment by timwis** [comment]
Just heard back from Nick at GitHub:

> I just wanted to follow up and let you know that the team pushed out an update to GitHub Pages early this morning. You should now receive a warning instead of a hard fail when using the theme: parameter.
> 
> Thanks for your patience, and for reporting this to us. Please let us know if there's anything else we can do for you!

So this should unbreak any existing JKAN forks. Woohoo!
