### ISSUE TITLE
Website: Add "who's using jkan"

### ISSUE THREAD

**Issue by timwis** [timwis/jkan#133]
I get this question often and it makes sense, particularly for organisations to ask. We should add a few to the homepage so folks feel like they're not completely out on their own using JKAN and they have peers they can reach out to if they need to. Here's a few recognisable organisations I know of:

- [San Diego](https://data.sandiego.gov/) (city government)
- [Open STL](http://openstl.org/) (local cfa brigade)
- [MySociety](http://data.mysociety.org/) (O.G. civic tech nonprofit)

**Comment by keeganmcbride** [comment]
Hey Tim.

In Estonia we are working on transitioning from our previous page open data portal (opendata.riik.ee) to one based on JKAN (https://keeganmcbride.github.io/jkan/).

**Comment by timwis** [comment]
Thanks great @keeganmcbride! Thanks for letting me know. Exciting to have you as users! I'm going to work on this section of the JKAN site this or next weekend.

**Comment by timwis** [comment]
Updated! Check out the redesigned https://jkan.io with "Who's using JKAN" :)

**Comment by keeganmcbride** [comment]
Will update once we switch over to more official URL ;)
