### ISSUE TITLE
For internal use only?

### ISSUE THREAD

**Issue by diazgilberto** [timwis/jkan#134]
What if an organization wants to use this applications to manage data catalogs for internal use only, just for people inside the organization. It is a way to install this application for internal use only?

**Comment by patcon** [comment]
This tool is great for putting in front of tools with no auth -- it allows authentication through a few whitelist options: https://github.com/bitly/oauth2_proxy

**Comment by timwis** [comment]
Nice resource, @patcon.

@diazgilberto I just wanted to add that ultimately JKAN is just a catalog website that points to data URLs. The easiest way to secure it is to secure the server hosting the data. For example, if you hosted your data on Google Drive, you could share it just within your GSuite organisation or with specific users, but still put the URL on your JKAN catalog. While the JKAN catalog would be public (if you knew the URL), once you click the data download link, Google would require you login and have access to download the file.

If you want your JKAN catalog website to be private, you should host the built version somewhere else, and secure it at the server level, say with HTTP Basic Auth. Let me know if you'd like me to elaborate on that.

Closing this for now but feel free to re-open if you still have questions.
