### ISSUE TITLE
Multiple categories filter

### ISSUE THREAD

**Issue by willemvanopstal** [timwis/jkan#136]
Is it possible to filter the datasets on multiple categories? 
Usually datasets do not simply 'fit' within one of the categories, therefore I'd like to be able to pick multiple categories and show the datasets which are in _all_ specified datasets. Maybe something with tags would also work fine.

Can this be achieved using the existing filter, or does it need a different architecture?

**Comment by timwis** [comment]
Hi @willemvanopstal,
Datasets can have multiple categories associated with them. For instance, in the demo, [airport runways](https://demo.jkan.io/datasets/airport-runways/) is associated with Real Estate / Land Records and Transportation ([here's the config](https://raw.githubusercontent.com/timwis/jkan-demo/gh-pages/_datasets/airport-runways.md)).

As for applying multiple category filters at the same time, JKAN doesn't do that out of the box. Frankly, unless you have _a ton_ of datasets, I would expect the need for this would be rather rare. But it's definitely possible if you don't mind dabbling in the JavaScript a bit. If you clone the repo, read over the [architecture page](https://github.com/timwis/jkan/wiki/Architecture) to understand how it works and get it running locally, then play around with [this section](https://github.com/timwis/jkan/blob/gh-pages/scripts/src/components/datasets-list.js#L26-L32) you should be able to get it to work. Let me know how you make out!

**Comment by willemvanopstal** [comment]
Thanks for the hints @timwis , will look into the pointers you gave me. Not really into javascript yet, but indeed it looks possible. I'll share the outcome whatever it is useful or not..

Regarding the functionality itself; I do like these tag-like categories since I'm building a portal for 'exploration'. Students come in with a basic idea of what they want to achieve and then strawl through the available datasets, because they don't have a clue about the huge availability (here in the Netherlands), they will not search for exact names but rather a combination of their interests; e.g. rasters+roads or pointclouds+indoor etc. (btw, it is kind of a special case only containing particular spatial datasets, divided in a lot of categories)

**Comment by timwis** [comment]
Sure thing. Let me know if you run into a wall and I can poke around a bit more so you can make it work for you.
