### ISSUE TITLE
Maintain data sets as CSV files in a repository

### ISSUE THREAD

**Issue by brockfanning** [timwis/jkan#141]
I'm just ramping up on JKAN, and from what I've seen the general use-case is maintaining metadata about data sets. Has anyone tried using JKAN to maintain data sets themselves, as CSV files in a repository? I'm thinking of functionality for editing tabular data in a user-friendly way, right in the JKAN interface. Is this possible/feasible in JKAN or is it out of scope?

**Comment by timwis** [comment]
Hi @brockfanning! You may want to check out octopub, mentioned the other day by @oxopendata in #140. Other related resources:

- [prose.io](http://prose.io), which has a [csv editor](https://github.com/prose/prose/pull/911)
- [okfn/dataexplorer](https://github.com/okfn/dataexplorer)
- [A pipe dream I had](https://github.com/prose/prose/issues/934)

There's some issues that git has with very large datasets, and there's probably a good case to keep your data in a repository outside of JKAN if you do go that route, but if you're just working with relatively small datasets or ones that don't update very often, I don't see why not. But I think folks at OKFN have explored this idea a lot more thoroughly.

**Comment by brockfanning** [comment]
Great info, thanks very much @timwis!
