### ISSUE TITLE
Input Mask

### ISSUE THREAD

**Issue by MatheusRV** [timwis/jkan#143]
Users can enter data in a way you find sometimes, for example an SSN can be typed as 404-05-9780 or 404059780. This will lead to an inconclusiveness of the data.

**Comment by timwis** [comment]
Hi! Can you elaborate on the issue you're describing? I don't understand how it pertains to JKAN.

**Comment by MatheusRV** [comment]
Some times field have mask like book ISBN, they need a model to fetch data.

**Comment by timwis** [comment]
Are you sure you're in the right repository? JKAN is an open data portal. It doesn't fetch data.
