### ISSUE TITLE
Hosting datasets

### ISSUE THREAD

**Issue by keeganmcbride** [timwis/jkan#150]
Just wondering why it hasn't been done (maybe there is a reason), but would it not make sense to make a /downloads folder, allow for files to be uploaded there, and then simply access via the base url/downloads/filename?

As some of our datasets did not have URLs, this is a strategy we pursued (https://github.com/okestonia/jkan/tree/master/downloads)

**Comment by loleg** [comment]
The big data problem is solvable with [Git LFS](https://git-lfs.github.com/). There's a nice tutorial from GitHub's staff here: https://github.community/t5/Support-Protips/Working-with-large-files-and-repositories/ba-p/9343

**Comment by jalbertbowden** [comment]
An alternative (imo preferred) solution to the big data problem is to split compression into multiple files, which can be dictated by a specified size.  
Certainly does not get around the speed issues mentioned previously, and I agree with the other idea about hosting the data separately.
That said, I use the compression trick all the time here. Below is a screenshot of Kika in OS X, set below GitHub's 100mb limit. You can also do this from cmd.  
![Screen Shot of Kika Archiver in OS X with a Per Compressed File Size Limitation Setting of 80mb](https://user-images.githubusercontent.com/46432/61571300-528c0080-aa60-11e9-8d64-1824c1745a02.png)

**Comment by keeganmcbride** [comment]
In our Estonian implementation, we have also started to see ministries host their OGD sets on GitHub and then provide this URL, for example: https://github.com/maanteeamet/opendata/tree/master/LIIKLUSREGISTER
