### ISSUE TITLE
Migrate to bootstrap4

### ISSUE THREAD

**Issue by keeganmcbride** [timwis/jkan#152]
Right now JKAN is using bootstrap 3, but the update to bootstrap 4 is not so time-intensive I believe. I am currently working on this and hope to make the PR in the next week or so once I have time to finish it off.

**Comment by timwis** [comment]
👏 that sounds great! thanks for putting in the time

**Comment by JackGilmore** [comment]
I can see there is a PR open for this (https://github.com/timwis/jkan/pull/153). Would it be possible to get this merged? @timwis
