### ISSUE TITLE
Management buttons should require collaborator access

### ISSUE THREAD

**Issue by timwis** [timwis/jkan#20]
Edit/add/delete/admin/setup buttons/pages

* Anonymous users: buttons should say "Suggest Changes" etc. and prompt them to login
* Logged-in users (non-collaborators): buttons should say "Suggest Changes" etc. and submit a pull request
* Logged-in Collaborators: buttons should say "Edit" etc. and make commits

**Comment by timwis** [comment]
This and #16 are complete pending michael/github#304 being merged

**Comment by JJediny** [comment]
Might it make sense to consider a hybrid of [liquid conditional logic](http://idratherbewriting.com/documentation-theme-jekyll/mydoc_conditional_logic/) coupled with the github.js to reduce the number of calls being made to github api (which could throttle over there allowed thresholds)?

**Comment by JJediny** [comment]
Disregard, as using liquid to hide the edit visibility would only work if essentially 2 views of the entire site we're to compiled one for view-only the other with edit. Seems appropriate to manage user state with JS and have that alter view/edit switching
