### ISSUE TITLE
does JKAN server host the data or is it just a list of links for data hosted somewhere else?

### ISSUE THREAD

**Issue by ilarimikkonen** [timwis/jkan#282]
sorry, did not understand that from the docs, is this where the links are maintained:

https://raw.githubusercontent.com/timwis/jkan/main/_datasets/sample-dataset.md

**Comment by timwis** [comment]
Hi @ilarimikkonen 👋🏻 It's the latter: JKAN is a catalogue of links to data hosted elsewhere. The data can be hosted basically anywhere: an S3 bucket, an SFTP server, web server, etc.

If you're after something more complex, like an API for the data, I'm happy to offer some open source options for that as well.

**Comment by ilarimikkonen** [comment]
Hi, thanks for a speedy response! this is exactly the type of an answer I was hoping to get. Please close the ticket per your process.

**Comment by timwis** [comment]
Sure thing. Feel free to reach out if you have any other questions or need a hand with anything! 👍🏻
