### ISSUE TITLE
Can't really change baseurl/auth settings from admin page

### ISSUE THREAD

**Issue by timwis** [timwis/jkan#29]
If `baseurl` isn't correct, the admin page doesn't save properly.

**Ideas**
1. Calculate `baseurl` dynamically by (1) checking if using custom domain or gh-pages, (2) checking if project page or org page
2. Document that this should be done _before_ changing the repo name
3. Move all JS code to `admin.html` to it doesn't depend on any other resources

EDIT: Just realized this applies to auth settings too, at least on the initial install...

Perhaps an `/install` page that prompts for these settings? Wizard could verify `client_id` is no longer than `x` characters (otherwise it's probably the secret)

**Comment by JJediny** [comment]
Not sure I understand the need, assuming a forked project can/will likely only need to make updates to _config.yml once or twice seems like alot of work to figure out a GUI solution to what can be semi-painlessly handled during installation with good docs

**Comment by timwis** [comment]
Update: this actually _does_ work if you go directly to the `/admin` page by typing it into the address bar. The links on the site just don't work.
