### ISSUE TITLE
Look into using oauth.io instead of gatekeeper

### ISSUE THREAD

**Issue by timwis** [timwis/jkan#31]

**Comment by JJediny** [comment]
http://passportjs.org/

**Comment by timwis** [comment]
That looks like a cool project! I actually came across that a couple weeks ago because the folks at 18F are using it for federalist. From what I read, though, it requires running a node/express.js server. OAuth.io appears to provide that "as a service."

**Comment by JJediny** [comment]
Yea i realized this after posting that something needs to be server-side... even if used for convince it might be best to use a service that can be used as a SaaS but that to can be self-served for those capable of managing their own Auth/Authorization. Does oauth.io offer a community edition?

**Comment by timwis** [comment]
Tried out auth.io and it may be a viable alternative to [gatekeeper](https://github.com/prose/gatekeeper), but the setup process wouldn't be much easier, in fact it may be a bit harder as crazy as that sounds. Let's see how far we can get with gatekeeper.
