### ISSUE TITLE
Use popup-based login instead of redirect

### ISSUE THREAD

**Issue by timwis** [timwis/jkan#32]
https://github.com/MrSwitch/hello.js/blob/55b89bf5487d4f39ff9a13b52498fbc976eb9fb7/src/hello.js#L1234

**Comment by JJediny** [comment]
bootstrap modal?

**Comment by timwis** [comment]
Hm, not sure that would work since the popup URL is a github.com login page. Perhaps through an iframe. Forgive the lack of context in the issue, posted it as a I was running out the door, but the reasoning for it is that the current login method (which I borrowed from prose.io and requirebin) involves redirecting the user to the github login page, then getting redirected back to JKAN, which checks for a `?code=` querystring. This works fine, but (a) you can't pass any other state back (like `gatekeeper_host` for #30), and (b) if the user shares their URL with someone while the code is in there, they're giving away access to their github account.

**Comment by timwis** [comment]
Decided against this because of how poor the experience would be on mobile
