### ISSUE TITLE
Submit Dataset Changes

### ISSUE THREAD

**Issue by iltempe** [timwis/jkan#57]
Hi!
Seems that the button Submit for dataset changes is not linked with any action. 
you can see my fork here. http://iltempe.github.io/opendatagentediprato/
Can you help me?
Congratulation, great work!

**Comment by timwis** [comment]
Thanks @iltempe!

It appears you've gone through the `/setup/` process and set the [authentication details](https://github.com/iltempe/opendatagentediprato/blob/gh-pages/_config.yml#L6-L7) properly. Are you logged in to your site when you click the _Submit_ button? Does it work when you do that?

Or are you pointing out that the submit button is available even when you're not logged in, and when you use it while not logged in, it doesn't work? If that's what you mean, we're aware: we just haven't hidden the form for non-logged-in users. The plan is actually to allow users to submit a pull request, per #20.

**Comment by iltempe** [comment]
Thanks!
For auth process i've setup

github_client_id: 94d5c2c76b1847f79b29
gatekeeper_host: opendatagentediprato

Maybe i've do something wrong in gatekeeper_host? I've deployed gatekeeper
on heroku. Which is the host to be used?

Thanks

2016-03-30 11:49 GMT+02:00 Tim Wisniewski <notifications@github.com>:

**Comment by timwis** [comment]
@iltempe it appears your authentication is working properly - I'm able to login. But as I'm not a collaborator on your repo, I don't have the ability to make changes. If you temporarily add me as a collaborator, I can make a change and verify whether I'm seeing anything unusual. I assume that you are logged in while you're trying to make a change to a dataset (it should show your github username at the top-right corner of the screen, where it used to show "Login").

By the way, I like the style improvements you've made to your site! And I'm glad to have the impetus for a language dictionary. I'll add an issue for that.

**Comment by iltempe** [comment]
ok. I've solved. I've not correctly setup HEROKU keywords. thanks a lot!

**Comment by timwis** [comment]
Oh, good to hear!
