### ISSUE TITLE
Use JavaScript-driven listings/filters/pagination

### ISSUE THREAD

**Issue by timwis** [timwis/jkan#7]
Enough fighting with jekyll and liquid. Just output the datasets as JSON and build the navigation with javascript.

**Comment by kuanb** [comment]
Was this a "tongue-in-cheek" issue? I see a pagination.html file in the source. Is this merely an appendage? 

Note: I concur that we should not fight Jekyll on this; was mostly interested in understand what the pagination.html file was doing.

**Comment by timwis** [comment]
Looks like we used it in `datasets.html` prior to 6b5a8124368c0761aeed192a4aa42aa6e1680ead. Somehow the file was never removed :O
