### ISSUE TITLE
Discussion: Is JKAN Production-ready?

### ISSUE THREAD

**Issue by timwis** [timwis/jkan#91]
Today's release is a release candidate for `v1.0.0`. The question to ask before declaring it `v1.0.0` is whether JKAN is production-ready. With this release candidate, all of the "entities" of JKAN are editable in the interface. The installation process is pretty well-guided. The architecture is well-documented and hopefully easy to dive into. What else is missing for a 1.0? Could someone in a government agency who isn't a software developer stand up an open data portal with it right now? Are there any other features/ideas that you brought up (or haven't yet) that you feel need to be part of a 1.0?

/cc @waldoj @pezholio @JJediny @mheadd @iltempe
(If you have a moment, I'd love your feedback)

**Comment by iltempe** [comment]
Good News!

I am a software developer and I have setup a data portal outside of my
government
agency of my city in Prato. I hope that my activity here wuold be useful to
make understandable how is simple to make data portal with JKAN. The portal
is http:\\iltempe.github.io\opendatagentediprato

I don't think is possible make additional modification now, but other
future improvements we can do in my opinion is something similar to a "CITY
DASHBOARD". I'm thinking to something like this
http://citydashboard.org/london/. The benefits are that the data portal
should be a website also to "view data" and make decisions in a simply way.

What do you think?

Regards

Matteo




2016-04-14 12:11 GMT+02:00 Tim Wisniewski <notifications@github.com>:

**Comment by mheadd** [comment]
@timwis This is some excellent work, the installation instructions are easy and worked like a charm.

That said, the first questions I asked myself after walking through the instructions and getting the site working were:

1. How do I add a new organization (I couldn't see how this could be done from the admin interface)?
2. How do I modify the look & feel (e.g., remove the "Fork Me" banner, which a user probably won't want on their site if they are using it for production).

These are minor, and the repo has all of the information needed to do this, but I think if the target audience here is a non-developer that wants to set up an open data portal in a few clicks then these are questions that should probably be addressed. Maybe there are a few more basic, getting started questions as well.

This suggests to me that some basic user documentation might be needed for a production launch.

Just my two cents.

**Comment by waldoj** [comment]
> (e.g., remove the "Fork Me" banner, which a user probably won't want on their site if they are using it for production).

:+1:

**Comment by mheadd** [comment]
@timwis I should say - happy to help with this user documentation if you need me, and you think its necessary. Just let me know.

**Comment by timwis** [comment]
Thanks for the feedback guys! @mheadd it looks like you may be running a version from a couple weeks ago, prior to the ability to create organizations being added. I've just submitted a pull request to your repo to update. Let me know if that makes it more clear for a first-time user how to add an organization.

Either way, I think you're right about the user docs. And I think we may as well remove the "fork me" banner entirely since jkan has a [homepage](https://jkan.io)

**Comment by timwis** [comment]
The "fork me" button has been removed, and the homepage is a little more exciting now with categories listed on it. There's also an easy way to change the look and feel through basic theme support (bootswatch). You can see it live at [demo.jkan.io](https://demo.jkan.io)

**Comment by iltempe** [comment]
Very Nice.

I’ve added some other icons and categories. http://iltempe.github.io/opendatagentediprato/ <http://iltempe.github.io/opendatagentediprato/>

https://github.com/iltempe/opendatagentediprato <https://github.com/iltempe/opendatagentediprato>

All icons are CC0 license.

Regards

**Comment by pezholio** [comment]
This is looking great now and more than production ready I think 👍

**Comment by timwis** [comment]
Thanks again for your feedback, everyone. Just cut `v1.0.0`
