### ISSUE TITLE
organizations.slug

### ISSUE THREAD

**Issue by iltempe** [timwis/jkan#92]
in last version I've notice that is added a field called organizations.slug. in organizations.html page.
What is that?
this creates an issue in links of my portal http://iltempe.github.io/opendatagentediprato/organizations/

can you help me?
thanks!

**Comment by iltempe** [comment]
ok. i've see. it's should be fixed as {{ organization.title | slugify }}

**Comment by timwis** [comment]
Thanks @iltempe - looks like the version of Jekyll that github runs doesn't support that property for some reason.

**Comment by timwis** [comment]
Should be fixed now
